# Change baseurl before deploy
baseurl = "https://dbednarekk.github.io/food_recipies/"
#baseurl = "localhost:1313/"
languageCode = "en-us"
title = "Food Recipies"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "pl"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
# disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5